CREATE TABLE `vend_brands` (
  `id` varchar(45) NOT NULL COMMENT 'Unique identifier for each vendor brand in the system.',
  `name` varchar(100) NOT NULL COMMENT 'The brand name of a vendor whose products are available for sale.',
  `deleted_at` varchar(45) DEFAULT NULL COMMENT 'Indicates when a brand was removed from active use in the system.',
  `version` varchar(45) NOT NULL,
  `enable_store_transfers` int(11) NOT NULL DEFAULT 1 COMMENT 'Indicates if products from this brand can be transferred between stores.',
  PRIMARY KEY (`id`),
  KEY `ix_vend_brands_enable` (`enable_store_transfers`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sentence: This table contains records of vape brands available for sale, used by the business to manage inventory and facilitate store transfers.  \nTags: Brand Management, Inventory Reports, Store Transfers, Active Brands, Brand Listings';

CREATE TABLE `vend_customers` (
  `id` varchar(45) NOT NULL COMMENT 'Unique identifier for each customer in the database.',
  `customer_code` varchar(100) DEFAULT NULL COMMENT 'Unique identifier for each customer used for tracking and reference in the system.',
  `first_name` mediumtext DEFAULT NULL COMMENT 'Stores the customer''s given name for identification and personalization in interactions.',
  `last_name` mediumtext DEFAULT NULL COMMENT 'Stores the customer''s family name for identification and communication purposes.',
  `email` varchar(100) DEFAULT NULL COMMENT 'Stores the customer''s email address for communication and account identification.',
  `year_to_date` varchar(45) DEFAULT NULL COMMENT 'Total purchases made by the customer this year in monetary value.',
  `balance` varchar(45) DEFAULT NULL COMMENT 'Outstanding amount the customer owes or credit they have with the company.',
  `loyalty_balance` varchar(45) DEFAULT NULL COMMENT 'Points accumulated by a customer for loyalty rewards.',
  `note` mediumtext DEFAULT NULL COMMENT 'Records important customer-related notes, such as underage or fraud alerts, for internal reference.',
  `gender` varchar(45) DEFAULT NULL COMMENT 'Indicates the customer''s gender for personalized marketing and communication.',
  `date_of_birth` varchar(45) DEFAULT NULL COMMENT 'Customer''s birth date for age verification and personalized marketing.',
  `company_name` varchar(100) DEFAULT NULL COMMENT 'Stores the name of the company associated with the customer for business reference.',
  `do_not_email` varchar(45) DEFAULT NULL COMMENT 'Indicates if a customer has opted out of receiving marketing emails.',
  `phone` varchar(100) DEFAULT NULL COMMENT 'Primary contact number for reaching the customer.',
  `mobile` varchar(100) DEFAULT NULL COMMENT 'Stores the customer''s mobile phone number for contact and communication purposes.',
  `physical_suburb` varchar(45) DEFAULT NULL COMMENT 'The suburb where the customer''s physical address is located.',
  `physical_city` varchar(45) DEFAULT NULL COMMENT 'Stores the city where the customer''s physical address is located for delivery and service purposes.',
  `physical_postcode` varchar(45) DEFAULT NULL COMMENT 'Stores the postcode for the customer''s physical address for delivery and location-based services.',
  `physical_state` varchar(45) DEFAULT NULL COMMENT 'Indicates the region or state where the customer''s physical address is located.',
  `postal_suburb` varchar(45) DEFAULT NULL COMMENT 'Stores the suburb part of a customer''s postal address for mailing purposes.',
  `postal_city` varchar(45) DEFAULT NULL COMMENT 'City for the customer''s postal address used for shipping and correspondence.',
  `postal_state` varchar(45) DEFAULT NULL COMMENT 'The state or region for the customer''s postal address used for shipping and correspondence.',
  `customer_group_id` varchar(45) DEFAULT NULL COMMENT 'Identifies the specific customer group for tailored marketing and sales strategies.',
  `enable_loyalty` varchar(45) DEFAULT NULL COMMENT 'Indicates if the customer is eligible to earn loyalty points.',
  `created_at` varchar(45) DEFAULT NULL COMMENT 'The date and time when the customer record was first created in the system.',
  `updated_at` varchar(45) DEFAULT NULL COMMENT 'Timestamp of the last update made to the customer''s record.',
  `deleted_at` varchar(45) DEFAULT NULL COMMENT 'Timestamp indicating when a customer record was marked as inactive or removed.',
  `version` varchar(45) DEFAULT NULL,
  `postal_postcode` varchar(45) DEFAULT NULL COMMENT 'Stores the postcode for the customer''s mailing address used for shipping and correspondence.',
  `name` mediumtext DEFAULT NULL COMMENT 'Full name of the customer for identification and communication purposes.',
  `physical_address_1` varchar(200) DEFAULT NULL COMMENT 'Stores the primary street address where the customer resides or receives deliveries.',
  `physical_address_2` varchar(200) DEFAULT NULL COMMENT 'Additional address details for customer deliveries or correspondence.',
  `physical_country_id` varchar(45) DEFAULT NULL COMMENT 'Stores the country code for the customer''s physical address location.',
  `postal_address_1` varchar(200) DEFAULT NULL COMMENT 'Primary line of the customer''s mailing address for shipping and correspondence.',
  `postal_address_2` varchar(200) DEFAULT NULL COMMENT 'Additional details for the customer''s mailing address, such as apartment or suite number.',
  `postal_country_id` varchar(45) DEFAULT NULL COMMENT 'Stores the country code for the customer''s postal address for shipping and communication purposes.',
  `custom_field_1` mediumtext DEFAULT NULL COMMENT 'This column stores miscellaneous customer notes or alerts for internal reference.',
  `custom_field_2` varchar(200) DEFAULT NULL,
  `custom_field_3` varchar(200) DEFAULT NULL,
  `custom_field_4` varchar(200) DEFAULT NULL,
  `website` varchar(200) DEFAULT NULL,
  `unsubscribe_account_balance` int(11) NOT NULL DEFAULT 0 COMMENT 'Indicates if a customer''s account balance should be excluded from email communications.',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `customerID` (`id`,`customer_code`,`email`),
  KEY `vs_code_idx` (`customer_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sentence: This table contains records of all customers who have made purchases at The Vape Shed, used for tracking customer information, purchase history, and loyalty program details.  \nTags: customer purchase history, loyalty program status, customer contact information, marketing preferences, customer demographics, sales reports, customer balance inquiries, birthday promotions, do not contact list.';

CREATE TABLE `vend_inventory` (
  `id` varchar(100) NOT NULL COMMENT 'Unique identifier for each inventory record in the system.',
  `outlet_id` varchar(100) NOT NULL COMMENT 'Identifies the specific store location where the product inventory is held.',
  `product_id` varchar(100) NOT NULL COMMENT 'Unique identifier for each product in the inventory system.',
  `inventory_level` int(11) NOT NULL COMMENT 'The current stock quantity of a product available at a specific outlet.',
  `current_amount` int(11) NOT NULL COMMENT 'The actual stock quantity available for a product at a specific outlet.',
  `version` bigint(20) NOT NULL,
  `reorder_point` int(11) DEFAULT NULL COMMENT 'Minimum stock level triggering a reorder to prevent product shortages.',
  `reorder_amount` int(11) DEFAULT NULL COMMENT 'The quantity of a product to order when stock reaches the reorder point.',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT 'Timestamp indicating when the inventory record was marked as inactive or removed.',
  `average_cost` decimal(16,6) NOT NULL COMMENT 'The average cost of acquiring a product, used for pricing and profitability analysis.',
  `sync_status` enum('synced','pending','failed','conflict') DEFAULT 'synced' COMMENT 'Tracks synchronization status with Vend API',
  `last_sync_attempt` timestamp NULL DEFAULT NULL COMMENT 'When sync was last attempted',
  `last_sync_success` timestamp NULL DEFAULT NULL COMMENT 'When sync was last successful',
  `last_sync_error` timestamp NULL DEFAULT NULL COMMENT 'When sync last failed',
  `pending_operation_id` varchar(100) DEFAULT NULL COMMENT 'Operation ID for pending sync operations',
  `vend_version_tracking` varchar(50) DEFAULT NULL COMMENT 'Vend record version for conflict detection',
  PRIMARY KEY (`id`),
  KEY `product_id` (`product_id`),
  KEY `outlet_id` (`outlet_id`),
  KEY `ix_vend_inventory_outlet_product` (`outlet_id`,`product_id`),
  KEY `ix_vend_inventory_level` (`inventory_level`),
  KEY `ix_vi_outlet_amt_prod` (`outlet_id`,`deleted_at`,`current_amount`,`product_id`),
  KEY `idx_vend_inventory_covering` (`product_id`,`outlet_id`,`inventory_level`),
  KEY `idx_sync_status` (`sync_status`,`last_sync_attempt`) COMMENT 'Fast lookup for sync monitoring dashboard',
  KEY `idx_pending_operations` (`pending_operation_id`,`sync_status`) COMMENT 'Fast lookup for pending operations cleanup'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sentence: This table contains records of inventory levels for products at various outlets, used by the business to manage stock levels and trigger reorders when necessary.  \nTags: inventory report, stock levels, reorder alerts, outlet inventory, product availability, stock management, reorder threshold, inventory audit, low stock warning, restock planning.';

CREATE TABLE `vend_outlets` (
  `id` varchar(100) NOT NULL COMMENT 'Unique identifier for each retail outlet in the system.',
  `register_id` varchar(100) DEFAULT NULL COMMENT 'Unique identifier for the cash register used at a specific retail outlet.',
  `name` varchar(100) NOT NULL COMMENT 'The name of the physical store location for inventory and sales tracking.',
  `default_tax_id` varchar(100) DEFAULT NULL COMMENT 'Identifies the tax rate applied by default to sales at this outlet.',
  `currency` varchar(100) DEFAULT NULL COMMENT 'The currency used for transactions at this outlet.',
  `currency_symbol` varchar(100) DEFAULT NULL COMMENT 'Symbol used to represent the currency for transactions at this outlet.',
  `display_prices` varchar(100) DEFAULT NULL COMMENT 'Indicates whether prices shown to customers include tax.',
  `time_zone` varchar(100) DEFAULT NULL COMMENT 'Indicates the local time zone for scheduling and coordinating store operations.',
  `physical_street_number` varchar(45) DEFAULT NULL COMMENT 'Stores the street number for the physical location of the vendor outlet.',
  `physical_street` varchar(45) DEFAULT NULL COMMENT 'Street name for the outlet''s physical location.',
  `physical_address_1` varchar(100) DEFAULT NULL COMMENT 'Stores the first line of the outlet''s physical address for location identification.',
  `physical_address_2` varchar(100) DEFAULT NULL COMMENT 'Additional address details for a vendor outlet, such as a building or unit name.',
  `physical_suburb` varchar(100) DEFAULT NULL COMMENT 'Identifies the suburb where the physical store is located for delivery and regional analysis.',
  `physical_city` varchar(255) DEFAULT NULL,
  `physical_postcode` varchar(100) DEFAULT NULL COMMENT 'The postcode for the physical location of the retail outlet.',
  `physical_state` varchar(100) DEFAULT NULL COMMENT 'Indicates the region or province where the outlet is located for logistical and reporting purposes.',
  `physical_country_id` varchar(100) DEFAULT NULL COMMENT 'Stores the country code where the physical outlet is located for business operations.',
  `physical_phone_number` varchar(45) DEFAULT NULL COMMENT 'Contact number for reaching the physical store location.',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT 'Timestamp indicating when the outlet was marked as inactive or removed from active use.',
  `version` bigint(20) NOT NULL,
  `turn_over_rate` float NOT NULL DEFAULT 5 COMMENT 'The rate at which inventory is sold and replaced at this outlet.',
  `automatic_ordering` int(11) NOT NULL DEFAULT 1 COMMENT 'Indicates if the outlet uses an automated system for placing stock orders.',
  `facebook_page_id` varchar(45) DEFAULT NULL COMMENT 'Unique identifier for the outlet''s Facebook page to manage social media presence and customer interactions.',
  `gss_token` varchar(100) DEFAULT NULL COMMENT 'Unique identifier for integrating Google services with the outlet.',
  `google_page_id` varchar(100) DEFAULT NULL COMMENT 'Unique identifier for the store''s Google business page, used for managing online presence and reviews.',
  `total_review_count` int(11) DEFAULT NULL COMMENT 'The total number of customer reviews received by this outlet.',
  `google_review_rating` float(2,1) DEFAULT NULL COMMENT 'Average customer rating for the outlet based on Google reviews.',
  `store_code` varchar(45) DEFAULT NULL COMMENT 'Unique identifier for each store location used in operations and reporting.',
  `magento_warehouse_id` int(11) DEFAULT NULL COMMENT 'Links each outlet to its corresponding warehouse in the Magento system.',
  `google_link` varchar(100) DEFAULT NULL COMMENT 'URL for the store''s Google Maps location to assist with navigation and customer visits.',
  `outlet_lat` varchar(45) DEFAULT NULL COMMENT 'Latitude coordinate for the outlet''s physical location.',
  `outlet_long` varchar(45) DEFAULT NULL COMMENT 'Geographical longitude coordinate for the outlet''s location.',
  `website_active` int(11) NOT NULL DEFAULT 1 COMMENT 'Indicates if the outlet''s website is currently active for online sales.',
  `website_outlet_id` int(11) DEFAULT NULL COMMENT 'Unique identifier for the outlet''s online presence within the company''s website system.',
  `deposit_card_id` int(11) DEFAULT NULL COMMENT 'Identifies the card used for deposits at this outlet for financial tracking.',
  `vape_hq_shipping_id` varchar(45) DEFAULT NULL COMMENT 'Unique identifier for tracking shipments from Vape HQ to this outlet.',
  `banking_days_allocated` int(11) NOT NULL DEFAULT 7 COMMENT 'Number of days allocated for banking transactions at this outlet.',
  `email` varchar(45) DEFAULT NULL COMMENT 'Email address for contacting the specific store location.',
  `nz_post_api_key` varchar(45) DEFAULT NULL COMMENT 'API key for accessing New Zealand Post services for shipping and logistics.',
  `nz_post_subscription_key` varchar(45) DEFAULT NULL COMMENT 'Unique identifier for managing NZ Post subscription services for each outlet.',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'Identifies the network location of the outlet for security and connectivity purposes.',
  `deputy_location_id` int(11) NOT NULL DEFAULT 0 COMMENT 'Links the outlet to its corresponding location in the Deputy workforce management system.',
  `eftpos_merchant_id` int(11) DEFAULT NULL COMMENT 'Unique identifier for processing card payments at this outlet.',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `is_warehouse` int(11) NOT NULL DEFAULT 0 COMMENT 'Indicates if the outlet functions as a warehouse (1 for yes, 0 for no).',
  PRIMARY KEY (`id`),
  UNIQUE KEY `register_id_UNIQUE` (`register_id`),
  UNIQUE KEY `magento_warehouse_id_UNIQUE` (`website_outlet_id`),
  KEY `ix_vend_outlets_warehouse` (`is_warehouse`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sentence: This table contains records of all retail outlets for The Vape Shed, used to manage and track store-specific operations and sales data.  \nTags: outlet locations, store management, sales by outlet, tax settings, currency settings, price display settings, store timezone settings';

CREATE TABLE `vend_products` (
  `id` varchar(100) NOT NULL DEFAULT '' COMMENT 'Unique identifier for each product entry in the system.',
  `source_id` varchar(200) DEFAULT NULL,
  `source_variant_id` mediumtext DEFAULT NULL COMMENT 'Unique identifier for a product variant from the original supplier or source.',
  `variant_parent_id` mediumtext DEFAULT NULL COMMENT 'Identifies the main product for which this item is a variant.',
  `name` varchar(255) DEFAULT NULL,
  `variant_name` varchar(255) DEFAULT NULL,
  `handle` varchar(200) DEFAULT NULL,
  `sku` varchar(200) DEFAULT NULL,
  `supplier_code` int(11) DEFAULT NULL COMMENT 'Unique identifier for the product''s supplier in the business system.',
  `active` int(11) NOT NULL COMMENT 'Indicates if the product is currently available for sale in the system.',
  `has_inventory` int(11) NOT NULL COMMENT 'Indicates if the product is currently in stock for sale.',
  `is_composite` int(11) NOT NULL COMMENT 'Indicates if the product is made up of multiple components or items.',
  `description` longtext DEFAULT NULL,
  `image_url` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Timestamp indicating when the product record was first added to the database.',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Timestamp of the last modification made to the product details.',
  `deleted_at` timestamp NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Timestamp indicating when the product was removed from active listings.',
  `type` mediumtext DEFAULT NULL,
  `account_code` mediumtext DEFAULT NULL,
  `version` bigint(20) NOT NULL,
  `supplier` mediumtext DEFAULT NULL COMMENT 'The supplier''s name for each product, used for ordering and inventory management.',
  `source` text DEFAULT NULL,
  `account_code_purchase` mediumtext DEFAULT NULL,
  `has_variants` mediumtext DEFAULT NULL COMMENT 'Indicates if the product has different versions or options available for sale.',
  `brand` varchar(255) DEFAULT NULL,
  `variant_options` text DEFAULT NULL,
  `brand_id` varchar(200) DEFAULT NULL COMMENT 'Unique identifier linking each product to its associated brand for inventory and reporting purposes.',
  `price_including_tax` decimal(13,5) NOT NULL COMMENT 'The total selling price of a product, including all applicable taxes.',
  `loyalty_amount` decimal(13,5) DEFAULT NULL COMMENT 'The loyalty amount awarded to customers for purchasing this product.',
  `price_excluding_tax` decimal(13,5) NOT NULL COMMENT 'The pre-tax selling price of a product for internal pricing and financial analysis.',
  `product_type_id` mediumtext DEFAULT NULL,
  `supplier_id` varchar(200) DEFAULT NULL COMMENT 'Unique identifier for the supplier providing this product.',
  `button_order` int(11) NOT NULL,
  `is_active` int(11) NOT NULL COMMENT 'Indicates whether the product is currently available for sale or use in operations.',
  `image_thumbnail_url` text DEFAULT NULL,
  `supply_price` decimal(13,5) NOT NULL COMMENT 'The cost price paid to suppliers for each product unit before any markup or taxes.',
  `avg_weight_grams` int(11) DEFAULT NULL,
  `dont_show_in_low_stock` int(11) NOT NULL DEFAULT 0 COMMENT 'Indicates if a product should be excluded from low stock alerts.',
  `dont_insert_into_website` int(11) DEFAULT 0 COMMENT 'Indicates if a product should be excluded from being listed on the website.',
  `harp_product_status` int(11) NOT NULL DEFAULT 0 COMMENT 'Indicates the product''s availability status in the HARP system.',
  `is_deleted` tinyint(1) GENERATED ALWAYS AS (`deleted_at` <> '0000-00-00 00:00:00') STORED,
  PRIMARY KEY (`id`),
  KEY `idx_supplier_active` (`supplier_id`,`is_active`,`active`,`deleted_at`),
  KEY `ix_vend_products_brand_supplier` (`brand_id`,`supplier_id`),
  KEY `ix_vend_products_deleted` (`deleted_at`),
  KEY `ix_vend_products_active` (`active`),
  KEY `ix_vp_flags` (`is_deleted`,`is_active`,`active`,`has_inventory`),
  KEY `idx_vend_products_active_inventory` (`active`,`has_inventory`,`is_active`,`supplier_id`,`brand_id`),
  FULLTEXT KEY `ProductFullSearch` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sentence: This table contains records of all products available for sale through The Vape Shed''s point-of-sale system, used for inventory management and sales tracking.  \nTags: product catalog, inventory list, sales tracking, product availability, stock management, product search, SKU lookup, variant details, pricing information, product updates';

CREATE TABLE `vend_sales` (
  `increment_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for each sale transaction in the system.',
  `id` varchar(36) NOT NULL COMMENT 'Unique identifier for each sale transaction in the system.',
  `outlet_id` varchar(36) NOT NULL COMMENT 'Identifies the specific store location where the sale was made.',
  `register_id` varchar(36) NOT NULL COMMENT 'Identifies the specific cash register used for the sale transaction.',
  `user_id` varchar(36) NOT NULL COMMENT 'Identifies the staff member who processed the sale transaction.',
  `customer_id` varchar(36) NOT NULL COMMENT 'Unique identifier for the customer associated with each sale transaction.',
  `invoice_number` int(11) NOT NULL COMMENT 'Unique identifier for each sales transaction invoice.',
  `status` varchar(30) NOT NULL COMMENT 'Indicates the current progress or completion stage of a sale transaction.',
  `note` mediumtext NOT NULL COMMENT 'Additional details or comments related to a specific sale transaction.',
  `short_code` varchar(15) NOT NULL COMMENT 'Unique identifier for quick reference to specific sales transactions.',
  `return_for` varchar(100) DEFAULT NULL COMMENT 'Links a sale to its original transaction when processing a return.',
  `total_price` decimal(16,6) DEFAULT NULL COMMENT 'The total amount charged for a sale, including any discounts or returns.',
  `total_tax` decimal(16,6) DEFAULT NULL COMMENT 'The total tax amount applied to a sale transaction.',
  `total_loyalty` decimal(16,6) DEFAULT NULL COMMENT 'The total loyalty points earned by the customer from this sale.',
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Timestamp of when the sale record was initially created in the system.',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Timestamp of the last modification made to the sales record.',
  `sale_date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'The date and time when the sale transaction was completed.',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT 'Timestamp indicating when the sale record was removed from active status.',
  `version` bigint(100) NOT NULL,
  `receipt_number` int(11) NOT NULL COMMENT 'Unique identifier for each sales transaction receipt issued to customers.',
  `version_max` bigint(100) DEFAULT NULL,
  `payments` longtext DEFAULT NULL,
  `sale_date_d` date GENERATED ALWAYS AS (cast(`sale_date` as date)) STORED,
  PRIMARY KEY (`increment_id`),
  UNIQUE KEY `SALE_ID_INDEX` (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `ix_vs_outlet_date_inc` (`outlet_id`,`sale_date`,`increment_id`),
  KEY `ix_vs_date_inc` (`sale_date`,`increment_id`),
  KEY `ix_vs_customer_date` (`customer_id`,`sale_date`),
  KEY `ix_vs_dateD_inc` (`sale_date_d`,`increment_id`),
  KEY `ix_vs_outlet_dateD_inc` (`outlet_id`,`sale_date_d`,`increment_id`),
  KEY `idx_vend_sales_performance` (`outlet_id`,`sale_date`,`status`,`total_price`),
  KEY `idx_vend_sales_user_date_status` (`user_id`,`created_at`,`status`),
  KEY `idx_vs_outlet_date_status` (`outlet_id`,`sale_date`,`status`),
  KEY `idx_vs_customer_date` (`customer_id`,`sale_date`),
  KEY `idx_vs_user_date_status` (`user_id`,`sale_date`,`status`),
  KEY `idx_vs_increment_outlet_date` (`increment_id`,`outlet_id`,`sale_date`),
  KEY `idx_sales_outlet_increment` (`outlet_id`,`increment_id`) USING BTREE,
  KEY `idx_vend_sales_web_processing` (`outlet_id`,`status`,`sale_date`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=1176280651 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sentence: This table contains records of individual sales transactions processed through the Vend point-of-sale system, used by the business to track sales performance, manage inventory, and analyze customer purchasing behavior.  \nTags: sales reports, transaction history, closed sales, sales by outlet, sales by register, customer purchase analysis, daily sales summary, sales performance, inventory management, sales status closed, sales status open.';

CREATE TABLE `vend_sales_line_items` (
  `sales_increment_id` int(11) NOT NULL COMMENT 'Unique identifier for each sales transaction line item in sequential order.',
  `id` varchar(36) NOT NULL COMMENT 'Unique identifier for each sales line item in the system.',
  `product_id` varchar(36) NOT NULL COMMENT 'Unique identifier for the product sold in each transaction line.',
  `tax_id` varchar(36) NOT NULL COMMENT 'Identifies the specific tax rate applied to the sale item for accurate tax calculation.',
  `discount_total` decimal(16,6) DEFAULT NULL COMMENT 'Total discount amount applied to the sale line item.',
  `discount` decimal(16,6) DEFAULT NULL COMMENT 'The discount applied to a single item in a sales transaction.',
  `price_total` decimal(16,6) DEFAULT NULL COMMENT 'The final sale price of a product line item after discounts and taxes.',
  `price` decimal(16,6) DEFAULT NULL COMMENT 'The selling price of a single unit of the product before discounts and taxes.',
  `cost_total` decimal(16,6) NOT NULL COMMENT 'The total cost incurred by the business for the items in a sales transaction.',
  `cost` decimal(16,6) NOT NULL COMMENT 'The purchase price of a single unit of the product sold in a transaction.',
  `tax_total` decimal(16,6) DEFAULT NULL COMMENT 'The total tax amount applied to this sales line item.',
  `tax` decimal(16,6) DEFAULT NULL COMMENT 'The tax amount applied to a specific product line in a sales transaction.',
  `quantity` int(11) NOT NULL COMMENT 'The number of units of a product sold in a single transaction.',
  `loyalty_value` decimal(16,6) DEFAULT NULL COMMENT 'The loyalty points earned from this sale line item for customer rewards.',
  `note` mediumtext DEFAULT NULL COMMENT 'Additional details or comments about the sale item for staff reference.',
  `price_set` int(11) NOT NULL COMMENT 'Indicates if the item''s price was manually adjusted during the sale.',
  `status` varchar(30) NOT NULL COMMENT 'Indicates the current processing stage of the sales line item in the transaction.',
  `sequence` int(11) NOT NULL COMMENT 'Indicates the order of items within a single sale transaction.',
  `unit_discount` decimal(16,6) DEFAULT NULL COMMENT 'The discount applied to each individual item in a sale transaction.',
  `unit_loyalty_value` decimal(13,5) NOT NULL COMMENT 'The loyalty points earned per unit of product sold.',
  `total_cost` decimal(16,6) DEFAULT NULL COMMENT 'The total expense incurred by the business for the items in this sales line.',
  `unit_price` decimal(16,6) DEFAULT NULL COMMENT 'The selling price of a single unit of a product before any discounts or taxes.',
  `unit_cost` decimal(16,6) DEFAULT NULL COMMENT 'The cost per unit for each product sold, used to calculate profit margins.',
  `total_discount` decimal(16,6) DEFAULT NULL COMMENT 'The total monetary value of all discounts applied to a sales line item.',
  `total_price` decimal(16,6) DEFAULT NULL COMMENT 'The final amount charged to the customer for this line item, including any discounts and taxes.',
  `total_loyalty_value` decimal(16,6) DEFAULT NULL COMMENT 'The total loyalty points earned from this sale line item for customer rewards.',
  `total_tax` decimal(16,6) DEFAULT NULL COMMENT 'The total tax amount applied to this sales line item for reporting and accounting purposes.',
  `is_return` int(11) NOT NULL COMMENT 'Indicates if the item was returned by the customer (1 for yes, 0 for no).',
  `unit_tax` decimal(16,6) DEFAULT NULL COMMENT 'The tax amount applied to a single unit of the product in a sale.',
  `sale_id` varchar(36) NOT NULL COMMENT 'Unique identifier linking each line item to its corresponding sale transaction.',
  PRIMARY KEY (`sales_increment_id`,`id`),
  KEY `idx_quantity_return` (`quantity`,`is_return`),
  KEY `idx_status` (`status`),
  KEY `idx_sale_id` (`sale_id`),
  KEY `ix_vsli_salesinc_prod_status_return` (`sales_increment_id`,`product_id`,`status`,`is_return`),
  KEY `idx_vsli_status_product` (`status`,`product_id`),
  KEY `idx_vsli_covering_agg` (`status`,`product_id`,`quantity`,`price_total`,`tax_total`),
  KEY `idx_vsli_sales_inc_status` (`sales_increment_id`,`status`),
  KEY `idx_sale_line_product_outlet` (`product_id`,`sales_increment_id`,`is_return`),
  KEY `idx_covering_ultra_fast` (`product_id`,`is_return`,`sales_increment_id`,`quantity`),
  CONSTRAINT `vendSaleIncrementID` FOREIGN KEY (`sales_increment_id`) REFERENCES `vend_sales` (`increment_id`),
  CONSTRAINT `vendUUIDIncrementID` FOREIGN KEY (`sale_id`) REFERENCES `vend_sales` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sentence: This table contains detailed records of individual items sold in each transaction, used for tracking sales performance and inventory management.  \nTags: sales report, transaction details, item sales analysis, inventory tracking, discount analysis, tax calculation, product performance';

CREATE TABLE `vend_suppliers` (
  `id` varchar(100) NOT NULL COMMENT 'Unique identifier for each supplier in the system.',
  `name` varchar(100) NOT NULL COMMENT 'The supplier''s business or brand name for identification and communication.',
  `source` varchar(45) DEFAULT NULL COMMENT 'Indicates the origin or method by which the supplier was added to the system.',
  `description` varchar(45) DEFAULT NULL COMMENT 'Provides a brief overview of the supplier''s product line or brand association.',
  `deleted_at` varchar(45) DEFAULT NULL COMMENT 'Indicates when a supplier was removed from active use in the system.',
  `version` varchar(45) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL COMMENT 'Supplier''s primary email address for communication and order processing.',
  `claim_email` varchar(150) DEFAULT NULL,
  `bank_account` varchar(45) DEFAULT NULL COMMENT 'Stores the supplier''s bank account details for processing payments.',
  `phone` varchar(45) DEFAULT NULL COMMENT 'Stores the contact number for reaching out to the supplier.',
  `contact_name` varchar(45) DEFAULT NULL COMMENT 'Name of the primary contact person for supplier communication.',
  `show_in_system` int(11) DEFAULT 1 COMMENT 'Indicates if the supplier is visible and active in the system for transactions and operations.',
  `automatic_ordering` int(11) NOT NULL DEFAULT 0 COMMENT 'Indicates if the supplier is set up for automatic order placement.',
  `automatic_transferring` int(11) NOT NULL DEFAULT 1 COMMENT 'Indicates if supplier transfers are automated within the system.',
  `automatic_transferring_based_on_sales_data` int(11) DEFAULT 0 COMMENT 'Indicates if stock transfers are triggered automatically based on sales trends.',
  `notification_eligible` int(11) NOT NULL DEFAULT 1 COMMENT 'Indicates if the supplier is eligible to receive notifications from the system.',
  `credit_sla_days` int(11) DEFAULT NULL,
  `enable_product_returns` int(11) NOT NULL DEFAULT 1 COMMENT 'Indicates if the supplier allows products to be returned.',
  `enable_wholesale_show_estimated_delivery` int(11) NOT NULL DEFAULT 0 COMMENT 'Indicates if wholesale customers can view estimated delivery dates for orders.',
  `automatic_ordering_moq` int(11) NOT NULL DEFAULT 30 COMMENT 'Minimum quantity required to trigger automatic ordering from this supplier.',
  `automatic_product_forecasting` int(11) NOT NULL DEFAULT 0 COMMENT 'Indicates if the supplier''s products are included in automated demand forecasting.',
  `website` varchar(45) DEFAULT NULL,
  `contact_person` varchar(45) DEFAULT NULL,
  `brand_logo_url` varchar(45) DEFAULT NULL,
  `primary_color` varchar(45) DEFAULT NULL,
  `secondary_color` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `ix_vend_suppliers_auto` (`automatic_transferring`),
  KEY `ix_vs_name` (`name`),
  KEY `ix_vs_email` (`email`),
  KEY `ix_vs_visible_name` (`show_in_system`,`name`),
  KEY `ix_vs_notify_enabled` (`notification_eligible`,`id`),
  KEY `ix_vs_returns_enabled` (`enable_product_returns`,`id`),
  KEY `ix_vs_auto_ordering` (`automatic_ordering`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sentence: This table contains records of suppliers from whom The Vape Shed sources products, used for managing supplier relationships and procurement processes.  \nTags: supplier list, active suppliers, supplier management, procurement, vendor contacts, supplier status, TVS range suppliers, supplier sourcing';

CREATE TABLE `purchase_orders_flagged` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `purchase_order_id` varchar(96) NOT NULL,
  `outlet_id` varchar(64) NOT NULL,
  `status` tinyint(4) DEFAULT 0,
  `flagged_reason` varchar(255) DEFAULT NULL,
  `flagged_notes` text DEFAULT NULL,
  `flagged_by` varchar(64) DEFAULT NULL,
  `flagged_at` datetime DEFAULT current_timestamp(),
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_po` (`purchase_order_id`),
  KEY `idx_outlet` (`outlet_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `purchase_orders` (
  `purchase_order_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for each purchase order in the system.',
  `outlet_id` varchar(100) NOT NULL COMMENT 'Unique identifier for the store location placing the purchase order.',
  `supplier_id` varchar(100) NOT NULL COMMENT 'Unique identifier for the supplier associated with the purchase order.',
  `supplier_name_cache` varchar(150) DEFAULT NULL,
  `date_created` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Last time this purchase order was updated',
  `deleted_by` int(11) DEFAULT NULL COMMENT 'User ID of staff who soft-deleted this purchase order',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT 'When the purchase order was soft deleted',
  `status` int(11) DEFAULT 0 COMMENT 'Indicates the current progress stage of a purchase order in the system.',
  `created_by` varchar(45) NOT NULL COMMENT 'Identifier for the staff member who initiated the purchase order.',
  `completed_by` varchar(100) DEFAULT NULL COMMENT 'The staff member responsible for finalizing the purchase order.',
  `completed_timestamp` timestamp NULL DEFAULT NULL COMMENT 'Timestamp when the purchase order was fully processed and completed.',
  `completed_notes` mediumtext DEFAULT NULL COMMENT 'Notes on discrepancies or issues encountered when completing a purchase order.',
  `receiving_started_by` varchar(45) DEFAULT NULL COMMENT 'Staff member who started the receiving process',
  `receiving_started_at` timestamp NULL DEFAULT NULL COMMENT 'When receiving process was initiated',
  `mobile_session_token` varchar(96) DEFAULT NULL COMMENT 'Token for mobile receiving session',
  `receiving_device_info` mediumtext DEFAULT NULL COMMENT 'JSON data about receiving device/browser',
  `receive_summary_json` longtext DEFAULT NULL CHECK (json_valid(`receive_summary_json`)),
  `api_id` varchar(45) DEFAULT NULL COMMENT 'Unique identifier for linking purchase orders to external systems or APIs.',
  `partial_delivery` int(11) NOT NULL DEFAULT 0 COMMENT 'Indicates if a purchase order has been partially delivered.',
  `partial_delivery_time` timestamp NULL DEFAULT NULL COMMENT 'Timestamp when a partial delivery of the order was received.',
  `partial_delivery_by` varchar(45) DEFAULT NULL COMMENT 'The staff member responsible for handling the partial delivery of an order.',
  `packing_slip_no` varchar(80) DEFAULT NULL,
  `invoice_no` varchar(80) DEFAULT NULL,
  `no_packing_slip` tinyint(1) NOT NULL DEFAULT 0,
  `totals_mode` enum('EX_GST','INC_GST') DEFAULT NULL,
  `subtotal_ex_gst` decimal(12,4) DEFAULT NULL,
  `gst` decimal(12,4) DEFAULT NULL,
  `total_inc_gst` decimal(12,4) DEFAULT NULL,
  `id` int(11) GENERATED ALWAYS AS (`purchase_order_id`) VIRTUAL,
  `created_at` datetime GENERATED ALWAYS AS (`date_created`) VIRTUAL,
  `completed_at` datetime GENERATED ALWAYS AS (`completed_timestamp`) VIRTUAL,
  `last_received_by` int(11) DEFAULT NULL,
  `last_received_at` datetime DEFAULT NULL,
  `unlocked_by` int(11) DEFAULT NULL,
  `unlocked_at` datetime DEFAULT NULL,
  `receiving_notes` mediumtext DEFAULT NULL,
  `receiving_quality` enum('poor','fair','good','excellent') DEFAULT NULL,
  PRIMARY KEY (`purchase_order_id`,`outlet_id`,`supplier_id`),
  UNIQUE KEY `id_UNIQUE` (`purchase_order_id`),
  KEY `ix_po_supplier_status_completed` (`supplier_id`,`status`,`completed_timestamp`),
  KEY `ix_po_outlet_status_created` (`outlet_id`,`status`,`date_created`),
  KEY `idx_po_status_created` (`status`,`date_created`),
  KEY `idx_po_api` (`api_id`),
  KEY `ix_po_status` (`status`),
  KEY `ix_po_date_created` (`date_created`),
  KEY `ix_po_partial` (`partial_delivery`),
  KEY `idx_po_receiving_started` (`receiving_started_by`,`receiving_started_at`),
  KEY `idx_po_mobile_token` (`mobile_session_token`)
) ENGINE=InnoDB AUTO_INCREMENT=13315 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sentence: This table contains records of purchase orders made by The Vape Shed to suppliers, used for tracking order status and managing inventory restocking.  \nTags: purchase order status, supplier orders, inventory restocking, pending orders, completed orders, order tracking, supplier management, order creation date, order completion date, purchase order reports.';

CREATE TABLE `purchase_order_line_items` (
  `product_id` varchar(100) NOT NULL COMMENT 'Unique identifier for each product in a purchase order line item.',
  `substitution_product_id` varchar(100) DEFAULT NULL,
  `purchase_order_id` int(11) NOT NULL COMMENT 'Links each line item to its corresponding purchase order for tracking and reference.',
  `order_qty` int(11) NOT NULL COMMENT 'The number of units ordered for a specific product in a purchase order.',
  `slip_qty` int(11) DEFAULT NULL,
  `order_purchase_price` decimal(10,4) NOT NULL,
  `qty_in_stock_before` int(11) DEFAULT NULL COMMENT 'The stock level of a product before receiving the current purchase order.',
  `qty_arrived` int(11) DEFAULT NULL COMMENT 'The number of items received from a supplier for a specific purchase order.',
  `damaged_qty` int(11) NOT NULL DEFAULT 0,
  `discrepancy_type` enum('OK','MISSING','SENT_LOW','SENT_HIGH','SUBSTITUTED','DAMAGED','UNORDERED') NOT NULL DEFAULT 'OK',
  `unit_cost_ex_gst` decimal(10,4) DEFAULT NULL,
  `line_note` varchar(255) DEFAULT NULL,
  `received_by` varchar(45) DEFAULT NULL COMMENT 'Staff member who received this line item',
  `received_at` timestamp NULL DEFAULT NULL COMMENT 'When this line item was processed',
  `barcode_scanned` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Whether barcode was scanned during receiving',
  `photo_evidence_count` int(11) NOT NULL DEFAULT 0 COMMENT 'Number of photos attached to this line item',
  `receiving_notes` mediumtext DEFAULT NULL COMMENT 'Additional notes during receiving process',
  `added_product` int(11) NOT NULL DEFAULT 0 COMMENT 'Indicates if the product was newly added to inventory with this order.',
  `unexpected_product` tinyint(1) NOT NULL DEFAULT 0,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Last time this PO line item was updated',
  `deleted_by` int(11) DEFAULT NULL COMMENT 'User ID of staff who soft-deleted this PO line item',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT 'When the PO line item was soft deleted',
  `qty_ordered` int(11) GENERATED ALWAYS AS (`order_qty`) VIRTUAL,
  `qty_received` int(11) GENERATED ALWAYS AS (`qty_arrived`) VIRTUAL,
  `has_damage` tinyint(1) DEFAULT NULL,
  `is_substitute` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`product_id`,`purchase_order_id`),
  KEY `purchaseOrderID_idx` (`purchase_order_id`),
  KEY `ix_poli_product` (`product_id`),
  KEY `idx_poli_unexpected` (`unexpected_product`),
  KEY `ix_poli_substitute` (`substitution_product_id`),
  KEY `idx_poli_received` (`received_by`,`received_at`),
  KEY `idx_poli_barcode` (`barcode_scanned`),
  KEY `idx_poli_photos` (`photo_evidence_count`),
  CONSTRAINT `purchaseOrderID` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`purchase_order_id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sentence: This table contains detailed records of each product line item included in purchase orders, used by the business to track inventory levels and manage supplier orders efficiently.  \nTags: purchase order details, inventory tracking, supplier management, order fulfillment, stock level updates, product arrival status, purchase order analysis';

CREATE TABLE `po_supplier_ratings` (
  `rating_id` int(11) NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int(11) NOT NULL,
  `supplier_id` int(11) NOT NULL,
  `rating` enum('excellent','good','fair','poor') DEFAULT 'good',
  `notes` mediumtext DEFAULT NULL,
  `rated_by` int(11) NOT NULL,
  `rated_at` datetime NOT NULL,
  PRIMARY KEY (`rating_id`),
  KEY `purchase_order_id` (`purchase_order_id`),
  CONSTRAINT `po_supplier_ratings_ibfk_1` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`purchase_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `po_settings` (
  `setting_id` int(11) NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(64) NOT NULL,
  `setting_value` varchar(255) NOT NULL,
  `scope` enum('global','outlet','user') DEFAULT 'global',
  `scope_id` int(11) DEFAULT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`setting_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `po_security_events` (
  `event_id` int(11) NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int(11) DEFAULT NULL,
  `event_type` varchar(64) NOT NULL,
  `event_data` longtext DEFAULT NULL CHECK (json_valid(`event_data`)),
  `triggered_by` int(11) DEFAULT NULL,
  `triggered_at` datetime NOT NULL,
  PRIMARY KEY (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `po_receiving_sim_sessions` (
  `sim_id` int(11) NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `notes` text DEFAULT NULL,
  `quality` enum('poor','fair','good','excellent') DEFAULT NULL,
  `items_count` int(11) NOT NULL DEFAULT 0,
  `is_partial` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`sim_id`),
  KEY `idx_po` (`purchase_order_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `po_receiving_sim_lines` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sim_id` int(11) NOT NULL,
  `product_id` varchar(64) NOT NULL,
  `expected_qty` int(11) NOT NULL DEFAULT 0,
  `received_qty` int(11) NOT NULL DEFAULT 0,
  `flags_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`flags_json`)),
  `line_note` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sim` (`sim_id`),
  CONSTRAINT `fk_sim_header` FOREIGN KEY (`sim_id`) REFERENCES `po_receiving_sim_sessions` (`sim_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `po_notes` (
  `note_id` int(11) NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int(11) NOT NULL,
  `line_item_id` int(11) DEFAULT NULL,
  `discrepancy_id` int(11) DEFAULT NULL,
  `event_id` int(11) DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `note_type` enum('general','line','discrepancy','event') DEFAULT 'general',
  `note` mediumtext NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`note_id`),
  KEY `purchase_order_id` (`purchase_order_id`),
  CONSTRAINT `po_notes_ibfk_1` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`purchase_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `po_evidence` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int(11) NOT NULL,
  `evidence_type` varchar(50) DEFAULT 'delivery',
  `file_path` varchar(500) NOT NULL,
  `description` text DEFAULT NULL,
  `uploaded_by` int(11) NOT NULL,
  `uploaded_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_po_id` (`purchase_order_id`),
  KEY `idx_uploaded_by` (`uploaded_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `po_email_ingest` (
  `ingest_id` int(11) NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int(11) NOT NULL,
  `email_from` varchar(128) DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `body` mediumtext DEFAULT NULL,
  `received_at` datetime NOT NULL,
  `processed` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`ingest_id`),
  KEY `purchase_order_id` (`purchase_order_id`),
  CONSTRAINT `po_email_ingest_ibfk_1` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`purchase_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `po_documents` (
  `document_id` int(11) NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int(11) NOT NULL,
  `document_type` enum('packing_slip','invoice','other') DEFAULT 'other',
  `file_path` varchar(255) NOT NULL,
  `uploaded_by` int(11) NOT NULL,
  `uploaded_at` datetime NOT NULL,
  PRIMARY KEY (`document_id`),
  KEY `purchase_order_id` (`purchase_order_id`),
  CONSTRAINT `po_documents_ibfk_1` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`purchase_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `po_discrepancies` (
  `discrepancy_id` int(11) NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int(11) NOT NULL,
  `line_item_id` int(11) DEFAULT NULL,
  `type` enum('missing','damaged','over','under','other') DEFAULT 'other',
  `description` mediumtext DEFAULT NULL,
  `discrepancy_note` mediumtext DEFAULT NULL,
  `detected_by` int(11) DEFAULT NULL,
  `detected_at` datetime NOT NULL,
  PRIMARY KEY (`discrepancy_id`),
  KEY `purchase_order_id` (`purchase_order_id`),
  CONSTRAINT `po_discrepancies_ibfk_1` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`purchase_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `po_attachments` (
  `attachment_id` int(11) NOT NULL AUTO_INCREMENT,
  `purchase_order_id` int(11) NOT NULL,
  `line_item_id` int(11) DEFAULT NULL,
  `document_type` enum('packing_slip','invoice','other') DEFAULT 'other',
  `file_path` varchar(255) NOT NULL,
  `uploaded_by` int(11) NOT NULL,
  `uploaded_at` datetime NOT NULL,
  PRIMARY KEY (`attachment_id`),
  KEY `purchase_order_id` (`purchase_order_id`),
  CONSTRAINT `po_attachments_ibfk_1` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`purchase_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
